# Generated by Django 5.0.6 on 2024-05-29 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
